<a href="https://colab.research.google.com/github/alessandrobachechi/Cosmo-Gen/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**






 Importa NumPy

In [ ]:
import numpy as np

# NumPy **Array**

# **np.array( )**

**Creating NumPy Arrays from Objects**

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9,]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **np.arange( )**

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# **np.zeros(( )) np.ones(( ))**

Generate arrays of zeros or ones.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# **np.linspace( )**



Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

Note that `.linspace()` includes the stop value.

# **.eye( )**

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# **.rand( )**

Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1).

In [ ]:
np.random.rand(2)

array([0.00708995, 0.32801386])

In [ ]:
np.random.rand(5,5)

array([[0.78542866, 0.62081473, 0.03577283, 0.38977063, 0.20989321],
       [0.04810065, 0.98117946, 0.5049931 , 0.64697364, 0.28713548],
       [0.10781305, 0.72289749, 0.20817392, 0.6315331 , 0.56133581],
       [0.41354324, 0.94623805, 0.07947251, 0.29728617, 0.90469442],
       [0.89670622, 0.18116388, 0.91370789, 0.61034895, 0.25718477]])

# **.randn( )**

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero are more likely to appear.

In [ ]:
np.random.randn(2)

array([-0.34071052, -0.41948927])

In [ ]:
np.random.randn(5,5)

array([[-2.0225306 ,  0.11318966,  0.28619738, -0.58866907,  0.07272833],
       [-0.03115677,  0.73731598, -1.19280854,  1.61679037,  0.83668706],
       [ 0.17794985,  0.98285432,  0.50316821, -0.6777575 ,  1.72212827],
       [ 0.97221857,  0.97666593, -1.86178886,  1.18508305, -1.09960172],
       [ 1.64668546,  1.55327601, -0.61561269, -1.98579607, -1.53314409]])

# **.randint( )**

Returns random integers from low (inclusive) to high (exclusive).

In [ ]:
np.random.randint(1,100)

45

In [ ]:
np.random.randint(0,100,10)

array([26, 96, 64,  2, 82, 38, 97, 45, 16, 65])

# **.seed( )**

Can be used to set the random state, so that the same "random" results can be reproduced

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# **arr.methods( )**

Let's discuss some useful attributes and methods for an array:

# **.reshape( )**

In [ ]:
arr = np.arange(25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# **.max( ), .min( ),. argmax( ), .argmin( )**

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
ranarr.max()

39

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

9

# **.shape( )**

Shape is an attribute that arrays have (not a method): dici solo queste sono le righe e queste le colonne

In [ ]:
arr = np.arange(25)

In [ ]:
arr.shape

(25,)

# **.dtype**

You can also grab the data type of the object in the array

In [ ]:
arr2 = np.array([1.2, 3.4, 5.6])

In [ ]:
arr2.dtype

dtype('float64')